#!/bin/sh

args=`getopt dhl:s: ${1+"$@"}` || exit 1
set -- $args

while [ $# -gt 0 ]; do
    case "$1"
    in -h)
	echo >&2 "usage: $0 [-dh] -l num [-s status] [files ...]"; exit
    ;; -d)
	delete=1
    ;; -l)
	lifter=$2; shift
    ;; -s)
	status=$2; shift
    ;; --)
	shift; break
    ;; *)
	break
    esac
    shift
done

if [ -z "$lifter" ] || [ -z "$delete" -a -z "$status" ]; then
    echo >&2 "usage: $0 [-dh] -l num [-s status] [files ...]"; exit 1
fi

lifter=`expr substr 000 1 \\( 3 - length "$lifter" \\)`$lifter
status=`echo "$status" | tr a-z A-Z`

for file; do
    if [ -z "$delete" ]; then
	if grep -q "^# Lifter0*$lifter:" "$file"; then
	    sed -i "s/^\\(# Lifter0*$lifter:\\) [A-Z]*/\\1 $status/" "$file"
	else
	    sed -i "0,/^<?/b
		    /^# Lifter[0-9]*:/b
		    i\\# Lifter$lifter: $status
		    :loop;N;b loop" "$file"

	    grep -q "^# Lifter0*$lifter:" "$file"

	    if [ $? = 1 ]; then
		echo >&2 "$0: $file: could not add lifter status"
	    fi
	fi
    else
	if grep -q "^# Lifter0*$lifter:" "$file"; then
	    sed -i "/^# Lifter0*$lifter:/d" "$file"
	else
	    echo >&2 "$0: $file: could not remove lifter status"
	fi
    fi
done
