#!/bin/sh

#
#  STEP 2:
#  convert all Stud.IP message strings into a binary format
#

LOCALE_RELATIVE_PATH="."

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.mo" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.mo" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.mo.old"
	msgfmt "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.mo"
done
